### PR TITLE
Experimental/gbiab.fixes

### PR DESCRIPTION
**Pull request by williamstark01**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
fix

_Include a short description_
update Anno script filename
set dbowner to $USER automatically

_Include links to JIRA tickets_

# Testing
_Have you tested it?_
:+1: 

# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Review by ens-carlos — APPROVED** [review]
Looks good. Thank you!

**Review by ens-ftricomi — CHANGES_REQUESTED** [review]
Could you please pull the latest code? I agree with your changes but I can't merge the Pr or we will miss the  changes in the latest commit, thanks

**Comment by williamstark01** [comment]
Since there are no conflicts with the base branch the merge will not lose any changes. (Merging to either direction will do the same thing essentially.)

**Comment by williamstark01** [comment]
All good after the merge.

**Pull request merged**
