### PR TITLE
Feature/star stringtie ise

### PR DESCRIPTION
**Pull request by leannehaggerty**

### CODE REVIEW

**Comment by leannehaggerty** [comment]
@jamie-m-a and @fergalmartin I'm merging my intron_supporting_evidence code in to this branch. My branch was created from a more recent dev/hive_master so all the updates from there will be merged in too. There's no conflicts though so should all be fine - just thought this should all be in one place before Jamie adds the rnaSamba stuff.

**Comment by thibauthourlier** [comment]
Hi Leanne, from which branch did you started working on? There is an awful lot of changes and I suspect most of them are not related to your changes. If you know which commits you did, maybe you could start with feature/star_stringtie and cherry pick your changes. That would make the life of the reviewer a lot easier
Just saw your comment...

**Comment by jamie-m-a** [comment]
Thanks for the heads up Leanne, fine by me.

**Comment by leannehaggerty** [comment]
Hi @thibauthourlier 
The changes between this and the ISE branch that I want to merge in are only in Genome_annotation_conf and HiveStar2Introns.pm.
I thought that, since we will be testing this, and will want to do a full run of the pipeline, we should probably also merge the more recent changes from dev/hive_master, which have been approved there via PRs anyway, so should all be safe.

**Comment by thibauthourlier** [comment]
My problem is not about the safety of the code added, it's about visibility. If this is merged, then more changes are done and finally merged into dev/hive_master, I am not sure that git will be clever enough to say, there is only five commits I need to merge. You already named two people so I guess they will review the code...

**Pull request closed without merging**
