### PR TITLE
Swap 'merged_bam_file' and 'fan_merge_analyses' analyses so 'merged_b…

### PR DESCRIPTION
**Pull request by ens-carlos**
…am_file' is not run if the condition checking for only 1 tissue present in 'fan_merge_analyses' is true. 'merged_bam_file' wrongly inserted an analysis for the inexistent merged file making the rnaseq healthchecks fail near the end of the pipeline.

### CODE REVIEW

**Comment by leannehaggerty** [comment]
Does this mean that, if only one rnaseq tissue is present, the merged file will not be created? Won't that cause problems downstream?

**Comment by leannehaggerty** [comment]
Has this been tested? Because I feel like there is an analysis that will use the file named "<uniq_info>.merged.1.bam", so if you don't create the merged bam file there may issue downstream right?

**Comment by ens-carlos** [comment]
> Has this been tested? Because I feel like there is an analysis that will use the file named "<uniq_info>.merged.1.bam", so if you don't create the merged bam file there may issue downstream right?

The production run for _Physeter catodon_ did not create the merged file even if the merged_bam_file analysis was run but it created the analysis "physeter_catodon_merged_rnaseq_bam" so the rnaseq_healthchecks analysis at the end of the pipeline failed because there was 1 logic name like "%merged%" instead of 4 (or 0 as it should be in this case). I could not find any other analysis failing in this case other than a small number of bam2introns as expected for other reasons. What would be the analysis which you think could fail?

**Comment by leannehaggerty** [comment]
Ok if the merged file isn't needed at all, then there shouldn't be a problem.

**Pull request merged**
