### PR TITLE
Update/gst

### PR DESCRIPTION
**Pull request by leannehaggerty**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
New features:
- Run GST in FinaliseDB
- Fix out-of-bounds repeats 
- Add MVP meta table updates (this should only be a temporary solution, as all meta table should be handled by assembly registry in near future)

NOTE: YOU WILL NEED https://github.com/Ensembl/core_meta_updates.git IN YOUR ENSCODE

# Testing
Pipeline: mysql://ensadmin:xxxxx@mysql-ens-genebuild-prod-4:4530/leanne_gca029281585v1_db_finalisation_pipe_test
Core db: gb2:leanne_gca029281585v1_core_test

# Assign to the weekly GitHub reviewer
Everyone must check on this and add a comment before it can be merged!

### CODE REVIEW

**Review by ens-ftricomi — COMMENTED** [review]
It looks good and this will speed up a lot the hand over! Thank you Leanne :)

**Review by rkverma1984 — COMMENTED** [review]
Looks good. Thank you Leanne!

**Review by swatiebi — COMMENTED** [review]
Looks good, thanks Leanne!

**Comment by vianeyBE** [comment]
This will definitely smooth the handover. Thanks, Leanne

**Review by EreboPSilva — APPROVED** [review]
Looks great to me. I'll implement the necessary changes into the configs for the annotations modules.

**Pull request merged**
