### PR TITLE
Update registry on completion of genebuild

### PR DESCRIPTION
**Pull request by ndliberial**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
new feature
_Include a short description_
This would update the assembly's status in the registry to "Completed" once genebuild is finished pre-handover
_Include links to JIRA tickets_
https://www.ebi.ac.uk/panda/jira/projects/ENSGENEBUI/issues/ENSGENEBUI-510?filter=allopenissues
# Testing
_Have you tested it?_
Yes, script was run on the registry database
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Comment by thibauthourlier** [comment]
Hi @ndliberial , it seems that you are missing the new script to actually update the database/spreadsheet

**Comment by ndliberial** [comment]
I have the scripts in the scripts directory. I think I missed adding it to the commit.Rejoice alwaysOn 8 Jul 2021 09:18, Thibaut Hourlier ***@***.***> wrote:
Hi @ndliberial , it seems that you are missing the new script to actually update the database/spreadsheet

**Comment by ndliberial** [comment]
Missing script now added

**Review by thibauthourlier — APPROVED** [review]
Sounds good to me

**Pull request merged**
