### PR TITLE
Removed max transcript length.

### PR DESCRIPTION
**Pull request by ens-carlos**

### CODE REVIEW

**Comment by thibauthourlier** [comment]
I think we need to assess the benefits of this MAX_TRANSCRIPT_LENGTH otherwise we will need to check every release if it needs to be updated

**Comment by ens-carlos** [comment]
I removed it because it was just used to keep part of the score in its decimal part so I used an alternative way to do this.

**Comment by thibauthourlier** [comment]
Can a transcript really have a length of 0 or lower?

**Comment by ens-carlos** [comment]
It shouldn't but it was just to avoid a potential division by zero warning or exception.

**Pull request merged**
