### PR TITLE
removed mouse set from birds

### PR DESCRIPTION
**Pull request by ens-ftricomi**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
fix
_Include a short description_
The mouse set is no longer used in the aves clade so it can be removed from sanity checks
_Include links to JIRA tickets_

# Testing
_Have you tested it?_
yes
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_
@swatiebi

### CODE REVIEW

**Comment by ens-ftricomi** [comment]
switched mouse to mammals and tested with one of the pipelines

**Review by swatiebi — APPROVED** [review]

**Comment by swatiebi** [comment]
Looks Good. Thank you Francesca.

**Comment by leannehaggerty** [comment]
Probably better for the bird uniprot set to be the check here. Are you seeing bird_ biotypes at this check?

**Comment by ens-ftricomi** [comment]
I have aves_biotypes, I will add them in another Pr. Sorry I forgot to check them

**Pull request merged**
