### PR TITLE
Store cesar projected genes ...

### PR DESCRIPTION
**Pull request by ens-carlos**
... regardless the existence of previously stored projected genes from other methods.

### CODE REVIEW

**Comment by thibauthourlier** [comment]
I'm not sure of the reason of the first check, why not simply store the gene without checking if it exists first? As said in the comments the logic_name will allow for filtering

**Comment by ens-carlos** [comment]
It's a check to prevent duplicates from retries.

**Comment by thibauthourlier** [comment]
I think it would be better to use pre_cleanup to delete the data from previous run as it looks like you know all the stable ids. If the job died while storing the exons, the transcript would exists. In the current check, you would not store the full model. Otherwise you could check the full model but that's probably more compute expensive

**Comment by thibauthourlier** [comment]
Could you please add some POD to the functions?

**Comment by ens-carlos** [comment]
I've just added the PODs and removed some unused subs.

**Review by thibauthourlier — APPROVED** [review]
That's amazing!!!! Thanks

**Pull request merged**
