### PR TITLE
Throw if real count is less than 2/3 of expected

### PR DESCRIPTION
**Pull request by thibauthourlier**

### CODE REVIEW

**Comment by thibauthourlier** [comment]
The reason for this check is to make sure that you have some synonyms. In human there is some patch on patches which are not loaded as we don't display them. Having a equal or die would make the module die even if you have all your synonyms loaded. The count of expected is the number of possible synonyms

**Comment by kbillis** [comment]
Should we add here another check related to GRC assemblies? something like: if ( $self->param('assembly_name')  =~ m/GRC/) {
$self->warning("There is a discrepancy between synonym counts: $counter instead of ".$self->param('synonym_count'));
} else {
$self->throw("You are missing some synonyms: $counter instead of ".$self->param('synonym_count'));
}

**Comment by thibauthourlier** [comment]
I don't think it's a good idea otherwise you will have to edit the file each time you find an assembly with a problem but the data was loaded correctly

**Comment by kbillis** [comment]
I think if the assembly has a problem - as you said,  the person should be aware of this problem. For this reason, I believe a throw (of a higher threshold) is a better idea. Otherwise, we might find the problem in datacheck/healthchecks.  I don't think we will avoid it.

**Pull request merged**
