### PR TITLE
Disconnect repeatmasker repbase jobs to reduce db connections

### PR DESCRIPTION
**Pull request by thibauthourlier**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
Update
_Include a short description_
Disconnect the repeatmasker repbase jobs as they take more than 15 minutes in average due to the usage of crossmatch
_Include links to JIRA tickets_
NA
# Testing
_Have you tested it?_
Yes
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Review by ens-ftricomi — COMMENTED** [review]
It looks good to me

**Comment by leannehaggerty** [comment]
So this disconnects from the server after 15 mins then reconnects when the repeatmasking is done? (sorry for my ignorance)

**Comment by thibauthourlier** [comment]
No it disconnects after all connections are idle and reconnects when needed. The 15 minutes is an arbitrary threshold where disconnecting is beneficial. If we need to reconnect every second we can overload the server.

**Review by leannehaggerty — APPROVED** [review]
Thank you, that makes sense then that you would not want it to be "switched on" when writing output! Cheers, looks good

**Pull request merged**
