### PR TITLE
update igtr data for mammals

### PR DESCRIPTION
**Pull request by ens-ftricomi**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
Update
_Include a short description_
The multi species dataset for Ig TR is old and  the IMGT dataset has been updated with new species not included in the previous dataset.  The mammals dataset has been downloaded and the headers cleaned to match the rules in  the fish dataset.
_Include links to JIRA tickets_

# Testing
_Have you tested it?_
yes I found more Ig TR models in the tamandua annotation
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_
@leannehaggerty @swatiebi

### CODE REVIEW

**Comment by leannehaggerty** [comment]
The default is the human file, do we have an idea of the representation in the new mammals file? Is it more appropriate for rodents than the human file?

**Comment by ens-ftricomi** [comment]
I will add a README in the IgTr folder with the list of species, I forgot to do that, mouse is present in the new set but I haven't tested it with a mouse yet.

**Comment by leannehaggerty** [comment]
RE: /hps/nobackup/flicek/ensembl/genebuild/blastdb/ig_tr_genes/imgt_mammals_ig_tr_README
So there are human sequences in the new file, does this make the human file a subset of the new file?
Since the new file contains sequences from rodents and primates, I think it would be appropriate to use for all the mammal sub-groups

**Comment by ens-ftricomi** [comment]
yes I followed the IMGT mammal that include human and mouse https://www.imgt.org/vquest/refseqh.html#refdir2 
I haven't tested it in all the clades but I am annotating birds that use human by default, I can try with one.
Moreover chatting with Swati I would like to include the chicken sequences in this set and test it for birds, hopefully we will align some sequence from there when the species is closer to gallus gallus. What do you think about it?

**Comment by ens-ftricomi** [comment]
added HAVANA sequences for human and mouse in the file

**Comment by ens-ftricomi** [comment]
already solved

**Pull request closed without merging**
