### PR TITLE
Remove the checksum for the fastq file that is deleted.

### PR DESCRIPTION
**Pull request by ens-carlos**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
Fix.
_Include a short description_
Assign the checksum correctly to each fastq file.
_Include links to JIRA tickets_
N/A.
# Testing
_Have you tested it?_
Yes, on xenopus_laevis.
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Review by thibauthourlier — CHANGES_REQUESTED** [review]
Is there a reason for not having three regex instead of one big regex?
It feels overcomplicated, as we expect the checksum and the files to have the sema number of "items", using a for loop is probably better. You could recreate the string directly instead of doing splices and a join later
A better solution but more work so I would say to avoid would be to not do the join but to directly do the split so it can be used in the write_output method

**Comment by ens-carlos** [comment]
The 3 conditions including a regex check that there is a fastq file whose name includes _1, a fastq file whose name includes _2 and a fastq file that does not have any _. Since it cannot be assumed that the order of these files will always be the same, this solution covers the cases where the files appear in any order. I've been thinking about an alternative regex to cover these cases but I think it would be too long and less readable.

I'll recreate the testing environment and data and try to merge the two loops into one and try to avoid using arrays by using strings directly.

**Comment by thibauthourlier** [comment]
Not knowing the order is a good reason for having multiple regexes

**Review by thibauthourlier — APPROVED** [review]
Looks good to me

**Pull request merged**
