### PR TITLE
Hotfix/bam2introns rebatch4state

### PR DESCRIPTION
**Pull request by ens-carlos**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
Fix.
_Include a short description_
It adds two more exception types to the set of exceptions that result in re-running with rebatching.
_Include links to JIRA tickets_
https://www.ebi.ac.uk/panda/jira/browse/ENSGENEBUI-543
# Testing
_Have you tested it?_
Yes, on salmon1.
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Review by kbillis — COMMENTED** [review]
I asked Carlos to see if we can use the timer that we have in modules/Bio/EnsEMBL/Analysis/Tools/Utilities.pm  instead of bam2intron specific one.

**Comment by ens-carlos** [comment]
I think the timer used in bam2introns is the same as the one in Utilities.pm since the one run for bam2introns corresponds to the one in the parent module https://github.com/Ensembl/ensembl-analysis/blob/7579b4d0fa49b27f6762100e8478545a8e456836/modules/Bio/EnsEMBL/Analysis/Runnable/BaseExonerate.pm#L289

I think my PR should be closed and a bugfix submitted instead in order to check that $p is defined just before calling p->state here:
https://github.com/Ensembl/ensembl-analysis/blob/5c085ac581f817d4a74c796ea0b0cabe6719c8a4/modules/Bio/EnsEMBL/Analysis/Tools/Utilities.pm#L1299

That would fix the issue in bam2introns since the job would be rebatched after catching the timer exception as it's already doing.

**Comment by thibauthourlier** [comment]
> I think my PR should be closed and a bugfix submitted instead in order to check that $p is defined just before calling p->state here:
> 
> https://github.com/Ensembl/ensembl-analysis/blob/5c085ac581f817d4a74c796ea0b0cabe6719c8a4/modules/Bio/EnsEMBL/Analysis/Tools/Utilities.pm#L1299
> 
> That would fix the issue in bam2introns since the job would be rebatched after catching the timer exception as it's already doing.

Sounds like a plan, I'm not sure I understand how $p can be undefined but I'm not a specialist in the ProcessTable module...

**Comment by kbillis** [comment]
Thanks Carlos. That makes sense. I think "defunct" means the process has been corrupted/died etc, but its child or parent process is still running and we want to catch and kill it.

**Pull request closed without merging**
