### PR TITLE
Hotfix/primate sanity checks

### PR DESCRIPTION
**Pull request by leannehaggerty**
# Requirements
When creating your Pull request, please fill out the template below:

# PR details
Fixing primate sanity checks, see ticket https://www.ebi.ac.uk/panda/jira/browse/ENSGENEBUI-970

# Testing
N/A - we will see in time

# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

### CODE REVIEW

**Review by thibauthourlier — CHANGES_REQUESTED** [review]
Could you please check the biotypes for layer and genebuilder? At the moment we are checking if we have more than 2140 transcripts

**Comment by leannehaggerty** [comment]
> Could you please check the biotypes for layer and genebuilder? At the moment we are checking if we have more than 2140 transcripts

You mean check that there are more than 2140 transcripts in total? Or just for the human_pe12 biotype? (I assume so because this check can only really be on the protein-to-genome stuff since everything else is conditional, right?)

In my example db there are only 2002 transcripts for human_pe12 in the layer db (but the final core numbers are good, if not a little inflated), that's why I went with 2000. What's the significance of 2140?

Then for gbuild, I went with 19000 protein-coding, because that's sensible for primates

**Comment by thibauthourlier** [comment]
With the changes, if you have 3000 genes with the correct numbers for IG/TR, human and rnaseq, the sanity check for layer will pass. It will fail later for genebuild as you don't have enough genes. So I thought more biotypes should be checked like the ones from projection

**Comment by leannehaggerty** [comment]
> With the changes, if you have 3000 genes with the correct numbers for IG/TR, human and rnaseq, the sanity check for layer will pass. It will fail later for genebuild as you don't have enough genes. So I thought more biotypes should be checked like the ones from projection

Sorry I see what you mean now. I've added projection biotypes for primates, since human projection in this case will be pretty reliable (we will soon find out how reliable)

**Review by thibauthourlier — APPROVED** [review]
Looks good to me

**Comment by thibauthourlier** [comment]
Just waiting for travis to be happy after my conflict fixing

**Pull request merged**
